/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import model.User;
import repository.MongoUserRepository;
import service.AuthenticationService;
/**
 *
 * @author HP
 */
public class LoginFrame extends JFrame {
    private JTextField txtUsername;
    private JPasswordField txtPassword;
    private JButton btnLogin;
    
    private AuthenticationService authService;
    
    public LoginFrame() {
      authService = new AuthenticationService(new MongoUserRepository());
        
        setTitle("Inicio de Sesión - Task Manager");
        setSize(300, 200);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void initComponents() {
        JPanel panel = new JPanel();
        panel.setLayout(null);
        
        JLabel lblUser = new JLabel("Usuario:");
        lblUser.setBounds(20, 20, 80, 25);
        panel.add(lblUser);
        
        txtUsername = new JTextField();
        txtUsername.setBounds(100, 20, 160, 25);
        panel.add(txtUsername);
        
        JLabel lblPass = new JLabel("Contraseña:");
        lblPass.setBounds(20, 60, 80, 25);
        panel.add(lblPass);
        
        txtPassword = new JPasswordField();
        txtPassword.setBounds(100, 60, 160, 25);
        panel.add(txtPassword);
        
        btnLogin = new JButton("Ingresar");
        btnLogin.setBounds(100, 100, 100, 25);
        btnLogin.addActionListener(e -> login());
        panel.add(btnLogin);
        
        add(panel);
    }
    
    private void login() {
        String username = txtUsername.getText();
        String password = new String(txtPassword.getPassword());
        
        User user = authService.authenticate(username, password);
        if (user != null) {
            JOptionPane.showMessageDialog(this, "Bienvenida " + user.getFullName());
            // Abrir ventana de tareas
            TaskFrame taskFrame = new TaskFrame(user);
            taskFrame.setVisible(true);
            this.dispose();  // Cerrar login
        } else {
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            new LoginFrame().setVisible(true);
        });
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

