/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.Task;
import model.User;
import repository.MongoTaskRepository;
import service.TaskService;
/**
 *
 * @author HP
 */
public class TaskFrame extends JFrame {
    private JTable tableTasks;
    private DefaultTableModel tableModel;
    private TaskService taskService;
    private User user;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public TaskFrame(User user) {
        this.user = user;
        taskService = new TaskService(new MongoTaskRepository());
        
        setTitle("Tareas Pendientes - " + user.getFullName());
        setSize(500, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        loadTasks();
    }
private void initComponents() {
        tableModel = new DefaultTableModel(new Object[]{"Descripción", "Fecha límite"}, 0);
        tableTasks = new JTable(tableModel);
        
        JScrollPane scrollPane = new JScrollPane(tableTasks);
        add(scrollPane);
    }
    
    private void loadTasks() {
        List<Task> tasks = taskService.getPendingTasks(user.getUsername());
        tableModel.setRowCount(0); // Limpiar tabla
        for (Task t : tasks) {
            tableModel.addRow(new Object[]{t.getDescription(), t.getDueDate()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
